import Head from 'next/head'

export default function HeadLoayout() {
  return (
    <Head>
      <title>cxcbv</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1"
      />
      {/* <meta
    httpEquiv="Content-Security-Policy"
    content="connect-src 'self' ws://176.124.99.109:8001/api ws://127.0.0.1:8000/api  wss:;"
  /> */}
      <link rel="icon" href="/favicon.svg" />
    </Head>
  )
}
