import Head from 'next/head'
import Router from 'next/router'
import { useState, useEffect, useRef } from 'react'
import Loader from '../auxiliary-elements/Loader/Loader'
import Header from '../Header/Header'
import Footer from '../Footer/Footer'
import KeyCodeInput from '../auxiliary-elements/Inputs/KeyCodeInput/KeyCodeInput'

export default function MainLayout({ children }) {
  const inputRef = useRef()
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    ;(async () => {
      const { MetacomCreate } = await import('../../hooks-utils/useMetacom')
      MetacomCreate()
    })()
    const start = () => {
      setLoading(true)
    }
    const end = () => {
      setLoading(false)
    }
    Router.events.on('routeChangeStart', start)
    Router.events.on('routeChangeComplete', end)
    Router.events.on('routeChangeError', end)
    return () => {
      Router.events.off('routeChangeStart', start)
      Router.events.off('routeChangeComplete', end)
      Router.events.off('routeChangeError', end)
    }
  }, [])

  return (
    <>
      <Head>
        <title>cxcbv</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1"
        />
        <meta
          httpEquiv="Content-Security-Policy"
          content="connect-src 'self' ws://176.124.99.109:8001/api ws://127.0.0.1:8000/api  wss:;"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header inputRef={inputRef} />
      <KeyCodeInput inputRef={inputRef} />
      {loading && <Loader />}
      {children}
      <Footer />
    </>
  )
}
