import Head from 'next/head'
import Router from 'next/router'
import { useState, useEffect, useRef } from 'react'
import Loader from '../auxiliary-elements/Loader/Loader'
import Header from '../Header/Header'
import Footer from '../Footer/Footer'
import KeyCodeInput from '../auxiliary-elements/Inputs/KeyCodeInput/KeyCodeInput'

export default function MainLayout({ children }) {
  const inputRef = useRef()

  const [loading, setLoading] = useState(false)
  useEffect(() => {
    const start = () => {
      console.log('start')
      setLoading(true)
    }
    const end = () => {
      console.log('findished')
      setLoading(false)
    }
    Router.events.on('routeChangeStart', start)
    Router.events.on('routeChangeComplete', end)
    Router.events.on('routeChangeError', end)
    return () => {
      Router.events.off('routeChangeStart', start)
      Router.events.off('routeChangeComplete', end)
      Router.events.off('routeChangeError', end)
    }
  }, [])
  return (
    <>
      <Head>
        <title>cxcbv</title>
        <meta name="description" content="Generated by create next app"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header inputRef={inputRef} />
      <KeyCodeInput inputRef={inputRef} />
      {loading && <Loader />} {children}
      <Footer />
    </>
  )
}
