import Head from 'next/head'
import React from 'react'
import { IntlProvider } from 'react-intl'
import useLang from '../../content/locale'
import Header from '../Header/Header'
import Footer from '../Footer/Footer'

export default function MainLayout({ children }) {
  const { messages, locale, defaultLocale } = useLang()

  return (
    <>
      <Head>
        <title>cxcbv</title>
        <meta name="description" content="Generated by create next app"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IntlProvider
        locale={locale}
        defaultLocale={defaultLocale}
        messages={messages}
      >
        <Header />
        {children}
        <Footer />
      </IntlProvider>
    </>
  )
}
